[project]
name = "bird-site"
version = "1.0.0"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.12.15",
    "aiosqlite>=0.21.0",
    "flask>=3.1.1",
    "gunicorn>=23.0.0",
    "pydantic>=2.11.7",
]
